### PR TITLE
Convert isValidClientBodyBufferSize to something more generic and use…

### PR DESCRIPTION
**Pull request by wayt**
**What this PR does / why we need it**:

This re-use the `isValidClientBodyBufferSize` for `client_max_body_size` configuration.

I'm make `isValidClientBodyBufferSize` more generic for that.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
Fixes https://github.com/Shopify/edgescale/issues/743
Fixes https://github.com/kubernetes/ingress-nginx/issues/2494

**Special notes for your reviewer**:

There is probably a race condition when loading Ingress and their annotation that makes the Proxy configuration empty instead of the default value.
This happens when having a lot of Ingress to configure with too tight CPU/Memory.

This does not solve the race condition, but avoid invalid nginx configuration because of that.

@Shopify/edgescale

### CODE REVIEW

**Comment by zrdaley** [comment]
I think that there should also be a warning log here: https://github.com/Shopify/ingress/pull/152/files#diff-652deabba49a2a87d4c5a79700dfa1e3R763

Otherwise when the race condition occurs there won't be any traceability.

**Comment by wayt** [comment]
@zrdaley https://github.com/Shopify/ingress/pull/152/files#diff-652deabba49a2a87d4c5a79700dfa1e3R764

**Comment by ElvinEfendi** [comment]
This looks good to me!

> There is probably a race condition when loading Ingress and their annotation that makes the Proxy configuration empty instead of the default value.

Can you elaborate? Do we not validate that specific annotation and allow empty value?

**Comment by wayt** [comment]
Closed in favor of the upstream one https://github.com/kubernetes/ingress-nginx/pull/3409

@ElvinEfendi The original issue I've been able to trace is that we generate the configuration for a list of ingress, it fails to find annotation for some of them:
https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/controller/controller.go#L261
and returns an empty Annotation https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/controller/store/store.go#L678

Since this error is only logged and doesn't remove the Ingress from the list, we end up with invalid nginx configuration.

I've not been able to trace the original race condition here. But I'll investigate both the k8s cache storage https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/controller/store/store.go#L254 and Ingress first loading.

**Pull request closed without merging**
