### PR TITLE
Hackdayzzz: ingress-nginx plugin system

### PR DESCRIPTION
**Pull request by ElvinEfendi**
Plan:

1. Build CRD to describe a plugin
2. Change controller to react on CRD and reconfigure Nginx
3. Lua code to load and run plugins

### CODE REVIEW

**Comment by ElvinEfendi** [comment]
The plugins are expected to be stored in `/etc/nginx/lua/plugins/<plugin name>` in the container.

<plugin name> has to be a valid folder name.

Inside every plugin folder there has to be `main.lua` file. `main.lua` is the entry point of the plugin. It should define a public function for every Nginx phase that it needs to run.

**Comment by ElvinEfendi** [comment]
How do we feed variables to plugins?

There can be two types of variables (1) module level variable (2) per phase variable

--

I think we can have controller to dynamically create i.e `vars.lua` file in the plugin directory based on CRD data. Then plugin manager would read that file and feed variables accordingly.

**Comment by ElvinEfendi** [comment]
How do we do app specific plugins?

maybe have the directory scheme as following instead of `/etc/nginx/lua/plugins`:

/etc/nginx/lua/plugins/shared/<plugin name>/
/etc/nginx/lua/plugins/<upstream name (something that's Ingress specific)>/<plugin name>/

This way in future we can also reimplement core modules as plugins into `/etc/nginx/lua/plugins/core/<plugin name>/`.

--

How would it look like from CRD perspective?

**Comment by alexkursell** [comment]
So since we seem to have settled on having a plugin CRD reference a single archive, here's what I'm currently thinking of for the CRD structure:

```yaml
apiVersion: nginx.ingress.kubernetes.io/v1alpha1
kind: IngressNginxPlugin
metadata:
  name: test-plugin
spec:
  archive: https://site.com/plugin.tar.gz
  sha256sum: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  vars:
    - name: foo
      value: 123
```

With a corresponding go struct like this:
```go
type IngressNginxPluginSpec struct {
	Archive   string                 `json:"archive,omitempty"`
	Sha256Sum string                 `json:"sha256sum,omitempty"`
	Vars      map[string]interface{} `json:"vars,"`
}
```

Everybody good with this?

**Pull request closed without merging**
